# Generated by Django 3.0.8 on 2020-07-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('products_list', models.ManyToManyField(blank=True, to='shop.Product')),
            ],
        ),
    ]
