# Generated by Django 3.2.2 on 2021-05-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210508_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='Czechia', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='desc',
            field=models.CharField(default='cash', max_length=255),
            preserve_default=False,
        ),
    ]
